apiVersion: v1
kind: Namespace
metadata: { name: shop, labels: { "app.kubernetes.io/part-of": robot-shop } }
---
apiVersion: v1
kind: Namespace
metadata: { name: data, labels: { "app.kubernetes.io/part-of": platform } }
